services:
  nginx:
    #image: nginx:latest
    build:
      context: ./nginx-conf
      dockerfile: Dockerfile
    container_name: llm-lb
    env_file:
      - .env
    # ports:
    #   - "8080:8080"
    #volumes:
      #- ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx-conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - flask-app
    extra_hosts:
      - "ia-engine:host-gateway"
      - "redis:host-gateway"
      - "ia-queue:host-gateway"
    # networks:
    #   - red_geolex
    network_mode: host

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - red_geolex

  flask-app:
    build:
      context: ./redis_queue
      dockerfile: dockerfile
    container_name: ia-queue
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    # environment:
    #   REDIS_HOST: host.docker.internal
    #   REDIS_PORT: 6379
    #   BALANCER_HOST: host.docker.internal
    #   BALANCER_PORT: 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - red_geolex
      
 
networks:
  red_geolex:
    external: true
