services:
  nginx:
    #image: nginx:latest
    build:
      context: ./nginx-conf
      dockerfile: dockerfile
    container_name: llm-lb
    # ports:
    #   - "8181:8080"
    #volumes:
      #- ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx-conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - flask-app
    extra_hosts:
      - "modulo-ia-django:host-gateway"
      - "redis:host-gateway"
      - "flask-app:host-gateway"
    # networks:
    #   - red_geolex
    network_mode: host

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - red_geolex

  flask-app:
    build:
      context: ./redis_queue
      dockerfile: dockerfile
    container_name: flask-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      BALANCER_HOST: host.docker.internal
      BALANCER_PORT: 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - red_geolex
      
 
networks:
  red_geolex:
    external: true
