services:
  nginx:
    image: nginx:latest
    container_name: llm-lb
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - red_prueba

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - red_prueba

  flask-app:
    build:
      context: ./redis_queue
      dockerfile: dockerfile
    container_name: flask-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BALANCER_HOST: nginx
      BALANCER_PORT: 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - red_prueba
      
 
networks:
  red_prueba:
    external: true
